/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecciones_peliculas;

import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author juare
 */
public class Info_Cuenta extends javax.swing.JFrame {

    /**
     * Creates new form Info_Cuenta
     */
    public Info_Cuenta() {
        initComponents();
    }
    private int indice = 0;
    private int max;
    int pk_usuario;
    Conexion cnn;
    ArrayList <String> fila;
    ArrayList <String> columna;
    ArrayList <String> tipo;
    ArrayList <String> proyeccion;
    ArrayList <String> sala;
    ArrayList <String> fecha;
    ArrayList <String> pk_ticket;
    
    Cartelera ct;
    String Usuario;
    public Info_Cuenta(Cartelera ct,String Usuario) {
        cnn = new Conexion("verison_1_2_3");
        cnn.conectar();
        this.Usuario = Usuario;
        this.ct = ct;
        initComponents();
        this.inicializarComponentes();
    }
    
    public void inicializarComponentes(){
        fila = new ArrayList();
        columna = new ArrayList();
        tipo = new ArrayList();
        sala = new ArrayList();
        fecha = new ArrayList();
        proyeccion = new ArrayList();
        pk_ticket = new ArrayList();
        usuariolbl.setText(Usuario);
        this.pk_usuario= cnn.BuscarPorUsuario(this.Usuario);
        cnn.ConsultarTicket(pk_usuario,"pk_id_boleto",pk_ticket);
        cnn.ConsultarTicket(pk_usuario,"fila", fila);
        cnn.ConsultarTicket(pk_usuario,"columna", columna);
        cnn.ConsultarTicket(pk_usuario,"tipo", tipo);
        cnn.ConsultarTicket(pk_usuario,"fk_id_proyeccion", proyeccion);
        cnn.ConsultarTicket(pk_usuario,"fecha_de_creacion", fecha);
  
        max = pk_ticket.size();
        InsertarValores(indice);
        
    }
    
    public void InsertarValores(int indice){
        
        this.ticket.removeAll();
        ticket.setBackground(new Color(111, 242, 181));
        ticket.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 16));
        ticket.setText("");
        if(max > 0){
        this.ticket.append("\tid: "+pk_ticket.get(indice)+"\n\n");
        this.ticket.append("\tUsuario: "+Usuario+"\n\n");
        this.ticket.append("\tfila: "+fila.get(indice)+"\n\n");
        this.ticket.append("\tcolumna: "+columna.get(indice)+"\n\n");
        this.ticket.append("\ttipo: "+tipo.get(indice)+"\n\n");
        this.ticket.append("\tsala: "+cnn.ProyeccionTicket(Integer.parseInt(proyeccion.get(indice)),"num_sala")+"\n\n");
        this.ticket.append("\tpelicula: "+cnn.ProyeccionTicket(Integer.parseInt(proyeccion.get(indice)),"nombre")+"\n\n");
        this.ticket.append("\tfecha: "+cnn.ProyeccionTicket(Integer.parseInt(proyeccion.get(indice)),"hora")+":");
        this.ticket.append(cnn.ProyeccionTicket(Integer.parseInt(proyeccion.get(indice)),"minutos")+"\t\t");
        this.ticket.append(cnn.ProyeccionTicket(Integer.parseInt(proyeccion.get(indice)),"dia")+"/");
        this.ticket.append(cnn.ProyeccionTicket(Integer.parseInt(proyeccion.get(indice)),"mes")+"/");
        this.ticket.append(cnn.ProyeccionTicket(Integer.parseInt(proyeccion.get(indice)),"anio")+"\n\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new Imagen("usuario.jpg");
        jButton1 = new javax.swing.JButton();
        usuariolbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ticket = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 450, 188, 68));

        usuariolbl.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        usuariolbl.setForeground(new java.awt.Color(255, 255, 255));
        usuariolbl.setText("usuario");
        jPanel1.add(usuariolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("tickets:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton2.setText("Anterior");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 188, 68));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton3.setText("Siguiente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, 188, 68));

        ticket.setBackground(new java.awt.Color(255, 255, 204));
        ticket.setColumns(20);
        ticket.setRows(5);
        jScrollPane2.setViewportView(ticket);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 183, 550, 350));

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton4.setText("Cancelar Ticket");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1039, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ct.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        indice--;
        System.out.println(""+indice);
        if(indice < 0){
            indice = max-1; 
        }
        this.InsertarValores(indice);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        indice++;           

        if(indice >= max){
            indice = 0;
        }
        this.InsertarValores(indice);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        cnn.borrarBoleto(Integer.valueOf(this.pk_ticket.get(indice)));
        this.inicializarComponentes();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info_Cuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea ticket;
    private javax.swing.JLabel usuariolbl;
    // End of variables declaration//GEN-END:variables
}
