/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecciones_peliculas;

import java.util.ArrayList;

/**
 *
 * @author juare
 */
public class Peliculas extends javax.swing.JFrame {

    
    public Peliculas() {
        initComponents();
        this.inicializarComponentes();
    }
    Menu_administrador MA;
    
    Conexion cnn;
    public Peliculas(Menu_administrador MA) {
        this.MA = MA;
        initComponents();
        cnn = new Conexion("verison_1_2_3");
        cnn.conectar();
        this.inicializarComponentes();
    }
    
    public void inicializarComponentes(){
        this.minutoscbb.removeAllItems();
        this.segundoscbb.removeAllItems();
        for(int i=0;i<60;i++){
            this.minutoscbb.addItem(String.valueOf(i));
            this.segundoscbb.addItem(String.valueOf(i));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new Imagen("fondo2.jpg");
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombretxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        añotxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        actortxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        directortxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        segundoscbb = new javax.swing.JComboBox<>();
        horascbb = new javax.swing.JComboBox<>();
        minutoscbb = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        generocbb = new javax.swing.JComboBox<>();
        clasificacioncbb = new javax.swing.JComboBox<>();
        aceptarbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        aceptarbtn1 = new javax.swing.JButton();
        aceptarbtn2 = new javax.swing.JButton();
        aceptarbtn3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Peliculas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 13, -1, 38));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        nombretxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(nombretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 161, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("año:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 60, 40));

        añotxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(añotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 161, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("segundos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        actortxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(actortxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 161, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("director:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        directortxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(directortxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 161, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("genero:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("clasificacion:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        segundoscbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        segundoscbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segundoscbbActionPerformed(evt);
            }
        });
        jPanel1.add(segundoscbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 60, 60));

        horascbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        jPanel1.add(horascbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 60, 60));

        minutoscbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        minutoscbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minutoscbbActionPerformed(evt);
            }
        });
        jPanel1.add(minutoscbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 60, 60));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("duracion:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("horas");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("minutos");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("actor:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        generocbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acción", "Aventuras", "Ciencia Ficcion", "Comedia", "No-ficcion", "Drama", "Fantasia", "Musical", "Suspenso", "Terror", "Sin Especificar" }));
        jPanel1.add(generocbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 160, 30));

        clasificacioncbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "B-12", "B-15", "C" }));
        jPanel1.add(clasificacioncbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 160, 30));

        aceptarbtn.setBackground(new java.awt.Color(255, 255, 204));
        aceptarbtn.setText("Agregar");
        aceptarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarbtnActionPerformed(evt);
            }
        });
        jPanel1.add(aceptarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 130, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 430, 190));

        aceptarbtn1.setBackground(new java.awt.Color(255, 255, 204));
        aceptarbtn1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        aceptarbtn1.setText("Aceptar");
        aceptarbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(aceptarbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 250, 140));

        aceptarbtn2.setBackground(new java.awt.Color(255, 255, 204));
        aceptarbtn2.setText("Eliminar");
        jPanel1.add(aceptarbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 130, 30));

        aceptarbtn3.setBackground(new java.awt.Color(255, 255, 204));
        aceptarbtn3.setText("Modificar");
        aceptarbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarbtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(aceptarbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void segundoscbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segundoscbbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_segundoscbbActionPerformed

    private void minutoscbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minutoscbbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minutoscbbActionPerformed

    private void aceptarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarbtnActionPerformed
        // TODO add your handling code here:
        ArrayList<String> valores = new ArrayList();
        valores.add(this.nombretxt.getText());
        valores.add(this.añotxt.getText());
        valores.add(this.directortxt.getText());
        valores.add(this.generocbb.getSelectedItem().toString());
        valores.add(this.actortxt.getText());
        valores.add(this.clasificacioncbb.getSelectedItem().toString());
        valores.add(this.horascbb.getSelectedItem().toString());
        valores.add(this.minutoscbb.getSelectedItem().toString());
        valores.add(this.segundoscbb.getSelectedItem().toString());
        cnn.funcionInsertar("InsertarPeliculas", valores);
    }//GEN-LAST:event_aceptarbtnActionPerformed

    private void aceptarbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarbtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarbtn3ActionPerformed

    private void aceptarbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarbtn1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MA.setVisible(true);
    }//GEN-LAST:event_aceptarbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Peliculas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarbtn;
    private javax.swing.JButton aceptarbtn1;
    private javax.swing.JButton aceptarbtn2;
    private javax.swing.JButton aceptarbtn3;
    private javax.swing.JTextField actortxt;
    private javax.swing.JTextField añotxt;
    private javax.swing.JComboBox<String> clasificacioncbb;
    private javax.swing.JTextField directortxt;
    private javax.swing.JComboBox<String> generocbb;
    private javax.swing.JComboBox<String> horascbb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> minutoscbb;
    private javax.swing.JTextField nombretxt;
    private javax.swing.JComboBox<String> segundoscbb;
    // End of variables declaration//GEN-END:variables
}
