/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecciones_peliculas;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class Salas extends javax.swing.JFrame {

    
    public Salas() {
        initComponents();
        this.inicializarComponentes();
    }
    Menu_administrador ma;
    Conexion cnn;
    public Salas(Menu_administrador ma) {
        cnn = new Conexion("verison_1_2_3");
        cnn.conectar();
        this.ma = ma;
        initComponents();
        this.inicializarComponentes();
    }
    
    
    
    public void inicializarComponentes(){
    
       // areatxt.setText(cnn.consultar());
        
        DefaultTableModel model = new DefaultTableModel();
        Salas_Table.setModel(model);   
        cnn.ConsultarSalas(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new Imagen("fondo4.jpg");
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        eliminarbtn = new javax.swing.JButton();
        modificarbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tipocbb1 = new javax.swing.JComboBox<>();
        modificarckb = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        Salas_Table = new javax.swing.JTable();
        numsp = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Salas");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("num:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 80, 60));

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 90, 40));

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton4.setText("Aceptar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 230, 150));

        eliminarbtn.setBackground(new java.awt.Color(204, 255, 204));
        eliminarbtn.setText("Eliminar");
        eliminarbtn.setEnabled(false);
        eliminarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarbtnActionPerformed(evt);
            }
        });
        jPanel2.add(eliminarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 90, 40));

        modificarbtn.setBackground(new java.awt.Color(204, 255, 204));
        modificarbtn.setText("Modificar");
        modificarbtn.setEnabled(false);
        modificarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarbtnActionPerformed(evt);
            }
        });
        jPanel2.add(modificarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 90, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setText("Tipo:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 80, 60));

        tipocbb1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        tipocbb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Común", "3D", "4D", "Premium" }));
        tipocbb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipocbb1ActionPerformed(evt);
            }
        });
        jPanel2.add(tipocbb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 200, 60));

        modificarckb.setText("Modificar");
        modificarckb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarckbActionPerformed(evt);
            }
        });
        jPanel2.add(modificarckb, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        Salas_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Salas_Table);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 320, 130));

        numsp.setEnabled(false);
        jPanel2.add(numsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ArrayList <String> valores = new ArrayList();
        String tipo = this.tipocbb1.getSelectedItem().toString();
        valores.add(tipo);
        cnn.funcionInsertar("InsertarSalas", valores);
       // areatxt.setText(cnn.consultar());
        DefaultTableModel model = new DefaultTableModel();
        Salas_Table.setModel(model);   
        cnn.ConsultarSalas(model);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void eliminarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarbtnActionPerformed
        // TODO add your handling code here:
        String tipo = this.tipocbb1.getSelectedItem().toString();
        int pk_id_seleccionada =Integer.valueOf(this.Salas_Table.getModel().getValueAt(this.Salas_Table.getSelectedRow(),0).toString());
        cnn.BorrarSala(pk_id_seleccionada);
        this.inicializarComponentes();
    }//GEN-LAST:event_eliminarbtnActionPerformed

    private void modificarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarbtnActionPerformed
        // TODO add your handling code here:
        String tipo = this.tipocbb1.getSelectedItem().toString();
        //System.out.println("tipo : "+tipo);
        int pk_id_seleccionada =Integer.valueOf(this.Salas_Table.getModel().getValueAt(this.Salas_Table.getSelectedRow(),0).toString());
        cnn.modificarSala(pk_id_seleccionada,tipo);
        this.inicializarComponentes();
    }//GEN-LAST:event_modificarbtnActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        this.dispose();
        ma.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void tipocbb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipocbb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipocbb1ActionPerformed
    int estado = 0;
    private void modificarckbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarckbActionPerformed
        // TODO add your handling code here:
        if(estado == 0){
          numsp.setEnabled(true);
          modificarbtn.setEnabled(true);
          eliminarbtn.setEnabled(true);
          estado = 1;
        }else{
          numsp.setEnabled(false);
          modificarbtn.setEnabled(false);
          eliminarbtn.setEnabled(false);
          estado = 0;
        }
        
    }//GEN-LAST:event_modificarckbActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Salas_Table;
    private javax.swing.JButton eliminarbtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarbtn;
    private javax.swing.JCheckBox modificarckb;
    private javax.swing.JSpinner numsp;
    private javax.swing.JComboBox<String> tipocbb1;
    // End of variables declaration//GEN-END:variables
}
