/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecciones_peliculas;

import java.awt.Color;
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/**
 *
 * @author juare
 */
public class Ticket extends javax.swing.JFrame {

    
    String Usuario;
    int pk_id_proyeccion;
    ArrayList <String> asientosF;
    ArrayList <String> asientosC;
    ArrayList <String> asientosT;

    
    public Ticket() {
        initComponents();
    }
    
    Compra cm;
    Conexion cnn;
    public Ticket(Compra cm,String Usuario,int pk_id_proyeccion,ArrayList<String> asientosF,ArrayList<String> asientosC,ArrayList<String> asientosT) {
        this.asientosF = asientosF;
        this.asientosC = asientosC;
        this.asientosT = asientosT;
        this.pk_id_proyeccion = pk_id_proyeccion;
        this.Usuario = Usuario;
        cnn = new Conexion("verison_1_2_3");
        cnn.conectar();
        this.cm = cm;
        initComponents();
        inicializarComponentes();
    }
    
       double subtotal; 
       String fecha_;
    
    public void inicializarComponentes(){
        this.peliculalbl.setText(cnn.ProyeccionTicket(pk_id_proyeccion,"nombre"));
        String hora = cnn.ProyeccionTicket(pk_id_proyeccion,"hora");
        String minuto = cnn.ProyeccionTicket(pk_id_proyeccion,"minutos");
        String dia = cnn.ProyeccionTicket(pk_id_proyeccion,"dia");
        String mes = cnn.ProyeccionTicket(pk_id_proyeccion,"mes");
        String año = cnn.ProyeccionTicket(pk_id_proyeccion,"anio");
        
        
        //double pago = Double.parseDouble(this.pagotxt.getText());
        //double cambio = pago - total;
        int cantidadN = 0;
        int cantidadA = 0;
        for(int i =0;i<asientosF.size();i++){
            if(asientosT.get(i).contains("adulto")){
              cantidadA++;
            }
            
            if(asientosT.get(i).contains("niño")){
            cantidadN++;
            } 
               
        }
        int precioA = 60;
        int precioN = 35;
        double subtotalA=cantidadA*precioA;
        double subtotalN=cantidadN*precioN;
        subtotal = subtotalA+subtotalN ;
        double iva = subtotal*0.16;
        DecimalFormat df = new DecimalFormat("#.0");
        double total = subtotal+iva;
        
        this.cantidadNtxt.setText(String.valueOf(cantidadN));
        this.cantidadAtxt.setText(String.valueOf(cantidadA));
        this.precioNtxt.setText(String.valueOf(precioN));
        this.precioAtxt.setText(String.valueOf(precioA));
        this.ivatxt.setText(String.valueOf(df.format(iva)));
        this.subtotalNtxt.setText(String.valueOf(subtotalN));
        this.subtotalAtxt.setText(String.valueOf(subtotalA));
        this.totaltxt.setText(String.valueOf(total));


        this.horariolbl.setText("fecha: "+dia+"/"+mes+"/"+año+"  hora:"+hora+":0"+minuto);
        fecha_ = "fecha: "+dia+"/"+mes+"/"+año+"  hora:"+hora+":0"+minuto;

        for(int i=0;i<asientosF.size();i++){
            System.out.println("pos: "+asientosF.get(i)+asientosC.get(i));
        }
        System.out.println("usuario:"+this.Usuario);
        System.out.println("id:"+this.pk_id_proyeccion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new Imagen("fondo6.jpg");
        peliculalbl = new javax.swing.JLabel();
        horariolbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cantidadNtxt = new javax.swing.JTextField();
        ivatxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        precioNtxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        subtotalNtxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        totaltxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        JPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ticket = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        cambiotxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        total2txt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        pagotxt = new javax.swing.JTextField();
        comprabtn = new javax.swing.JButton();
        jCheckBox3 = new javax.swing.JCheckBox();
        cantidadAtxt = new javax.swing.JTextField();
        precioAtxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        subtotalAtxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        peliculalbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        peliculalbl.setText("Shrek");
        jPanel1.add(peliculalbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        horariolbl.setText("3:00");
        jPanel1.add(horariolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Pelicula:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Subtotal");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        jLabel5.setText("Horario:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("cantidad");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("x");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        cantidadNtxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cantidadNtxt.setText("2");
        cantidadNtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadNtxtActionPerformed(evt);
            }
        });
        jPanel1.add(cantidadNtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        ivatxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ivatxt.setText("$920");
        ivatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ivatxtActionPerformed(evt);
            }
        });
        jPanel1.add(ivatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 282, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Precio");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("=");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        precioNtxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        precioNtxt.setText("$60");
        precioNtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioNtxtActionPerformed(evt);
            }
        });
        jPanel1.add(precioNtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("+IVA=");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        subtotalNtxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        subtotalNtxt.setText("$9200");
        subtotalNtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotalNtxtActionPerformed(evt);
            }
        });
        jPanel1.add(subtotalNtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jSeparator1.setAlignmentY(1.0F);
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 72, 10));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("Forma de pago");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        totaltxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        totaltxt.setText("$10120");
        totaltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaltxtActionPerformed(evt);
            }
        });
        jPanel1.add(totaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Total =");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 336, -1, -1));

        jCheckBox1.setText("Tarjeta ");
        jCheckBox1.setEnabled(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, -1, -1));

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Efectivo");
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        ticket.setEditable(false);
        ticket.setColumns(20);
        ticket.setRows(5);
        ticket.setTabSize(5);
        jScrollPane1.setViewportView(ticket);

        javax.swing.GroupLayout JPanel1Layout = new javax.swing.GroupLayout(JPanel1);
        JPanel1.setLayout(JPanel1Layout);
        JPanel1Layout.setHorizontalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        JPanel1Layout.setVerticalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        jPanel1.add(JPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 390, 390));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        cambiotxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cambiotxt.setText("0");
        cambiotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiotxtActionPerformed(evt);
            }
        });
        jPanel1.add(cambiotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 90, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setText("Cambio=");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setText("Total =");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        total2txt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        total2txt.setText("$0");
        total2txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total2txtActionPerformed(evt);
            }
        });
        total2txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                total2txtKeyTyped(evt);
            }
        });
        jPanel1.add(total2txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 90, -1));

        jSeparator2.setAlignmentY(1.0F);
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 72, 10));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setText("Su pago= ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        pagotxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pagotxt.setText("0");
        pagotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagotxtActionPerformed(evt);
            }
        });
        jPanel1.add(pagotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 90, -1));

        comprabtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        comprabtn.setText("hacer compra");
        comprabtn.setEnabled(false);
        comprabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprabtnActionPerformed(evt);
            }
        });
        jPanel1.add(comprabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, -1, -1));

        jCheckBox3.setText("cambio");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        cantidadAtxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cantidadAtxt.setText("2");
        cantidadAtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadAtxtActionPerformed(evt);
            }
        });
        jPanel1.add(cantidadAtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        precioAtxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        precioAtxt.setText("$60");
        precioAtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioAtxtActionPerformed(evt);
            }
        });
        jPanel1.add(precioAtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel17.setText("x");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel18.setText("=");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        subtotalAtxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        subtotalAtxt.setText("$9200");
        subtotalAtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotalAtxtActionPerformed(evt);
            }
        });
        jPanel1.add(subtotalAtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        jLabel1.setText("niño");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel2.setText("adulto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1066, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantidadNtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadNtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadNtxtActionPerformed

    private void ivatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ivatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ivatxtActionPerformed

    private void precioNtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioNtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioNtxtActionPerformed

    private void subtotalNtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotalNtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotalNtxtActionPerformed

    private void totaltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totaltxtActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void cambiotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cambiotxtActionPerformed

    private void total2txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total2txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total2txtActionPerformed

    private void pagotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagotxtActionPerformed

    private void total2txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_total2txtKeyTyped
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_total2txtKeyTyped

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
        double Cambio = 0.0;
        double pago = 0.0;
        double total = 0.0;
        pago = parseDouble(this.pagotxt.getText());
        this.total2txt.setText(totaltxt.getText());
        total = parseDouble(total2txt.getText());
        DecimalFormat df = new DecimalFormat("#.0");
        
        Cambio = pago-total;
        
         this.cambiotxt.setText(String.valueOf(df.format(Cambio)));
        if(pago > total){
          comprabtn.setEnabled(true);
          pagotxt.setEditable(false);
          total2txt.setEditable(false);
          cambiotxt.setEditable(false);
        }else{
          comprabtn.setEnabled(false);
          pagotxt.setEditable(true);
          total2txt.setEditable(true);
          cambiotxt.setEditable(true);

        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void cantidadAtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadAtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadAtxtActionPerformed

    private void precioAtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioAtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioAtxtActionPerformed

    private void subtotalAtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotalAtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotalAtxtActionPerformed

    private void comprabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprabtnActionPerformed
        // TODO add your handling code here:
        LocalDateTime horaactual = LocalDateTime.now();
        String dia= String.valueOf(horaactual.getDayOfMonth());
        String mes= String.valueOf(horaactual.getMonthValue());
        String año= String.valueOf(horaactual.getYear());
        String hora=String.valueOf(horaactual.getHour());
        String minuto=String.valueOf(horaactual.getMinute());
        String segundo=String.valueOf(horaactual.getSecond());
        String salas1 =cnn.ProyeccionTicket(pk_id_proyeccion,"nombre");
        String sala2 = cnn.ProyeccionTicket(pk_id_proyeccion,"num_sala");
        ticket.setBackground(new Color(111, 242, 181));
        ticket.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 16));
        ticket.setText("\n\n\n");
        ticket.append("MOVIEMATIC\n\n");
        ticket.append("AV. Politecnico #2 Col.Ticoman\n Mexico DF C.P. 54170\n\n"); 
        ticket.append("   Fecha: " +dia+ "/" +mes+ "/" + año+"  "+"Hora: "+hora+":"+minuto+":"+segundo+"\n\n\n");
        ticket.append("Pelicula:  "+salas1+"\n");
        ticket.append("Funcion: "+fecha_+"\n");
        ticket.append("Sala  "+sala2+"\n");
        ticket.append("Boleto Adulto \n");
        for(int i =0;i<asientosF.size();i++){
            if(asientosT.get(i).contains("adulto")){
            ticket.append("fila: "+asientosF.get(i)+" columna: "+asientosC.get(i)+"\n");
            }     
        }
        ticket.append("Boleto niño\n");
        for(int i =0;i<asientosF.size();i++){ 
            if(asientosT.get(i).contains("niño")){
            ticket.append("fila: "+asientosF.get(i)+"columna:"+asientosC.get(i)+"\n");
            }        
        }
        ticket.append("     Subtotal ................. $  "+this.subtotal+"\n");
        ticket.append("     IVA ...................... $  "+ivatxt.getText()+"\n");
        ticket.append("     Total a pagar ............ $  "+totaltxt.getText()+"\n\n");
        ticket.append("          Efectivo ............ $  "+pagotxt.getText()+"\n");
        ticket.append("         Cambio  .............. $   "+cambiotxt.getText()+"\n\n\n");
        ticket.append("    ¡Gracias por su eleccion!\n");
        ticket.append("    www.moviematic.com.mx\n\n\n");
        int pk_usuario = cnn.BuscarPorUsuario(this.Usuario);

        for(int i =0;i<asientosF.size();i++){
        ArrayList <String> valores = new ArrayList();
        valores.add(asientosF.get(i));
        valores.add(asientosC.get(i));
        valores.add(asientosT.get(i));
        valores.add(dia+ "/" +mes+ "/" + año+"  "+"Hora:"+hora+":"+minuto+":"+segundo);
        valores.add(String.valueOf(this.pk_id_proyeccion));
        valores.add(String.valueOf(pk_usuario));
        cnn.funcionInsertar("Insertar_boleto", valores);
        }
   
    }//GEN-LAST:event_comprabtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here
        this.cm.dispose();
        this.dispose();
        this.cm.cm.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel1;
    private javax.swing.JTextField cambiotxt;
    private javax.swing.JTextField cantidadAtxt;
    private javax.swing.JTextField cantidadNtxt;
    private javax.swing.JButton comprabtn;
    private javax.swing.JLabel horariolbl;
    private javax.swing.JTextField ivatxt;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField pagotxt;
    private javax.swing.JLabel peliculalbl;
    private javax.swing.JTextField precioAtxt;
    private javax.swing.JTextField precioNtxt;
    private javax.swing.JTextField subtotalAtxt;
    private javax.swing.JTextField subtotalNtxt;
    private javax.swing.JTextArea ticket;
    private javax.swing.JTextField total2txt;
    private javax.swing.JTextField totaltxt;
    // End of variables declaration//GEN-END:variables
}
